apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: greetings
  namespace: default
spec:
  type: bindings.http
  version: v1
  metadata:
  - name: url
    value: https://raw.githubusercontent.com